version: 1.0.{build}
branches:
  only:
  - blueprint
skip_tags: true
image: Visual Studio 2017

environment:
  REPO_SLUG: vicr123/theInstaller
  GITHUB_TOKEN:
    secure: S0/npu2fzXbSoS8kfbLQFCjeMpYFVyllUubJYIUG/QEfT2L2bMQQ9A3OjbDsuH/p
  api_token:
    secure: hVbnQbmIi8N/AfopJa7JeE4CGLdb4CoXFHWKMvD9TNg=
  deploy_project: theinstaller
  deploy_version: ''
  deploy_artifact: ''
    
build_script:
- cmd: >-
    appveyor\build.bat

test: off

artifacts:
- path: deploy\theSlate.exe
  name: theSlate.exe
- path: deploy\thePhoto.exe
  name: thePhoto.exe
  
before_deploy:
- ps:
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/deploy.ps1'))
    
deploy_script:
- ps: >-
    
    Start-FileDownload 'https://github.com/probonopd/uploadtool/raw/master/upload.sh'
    
    sh -c "TRAVIS_BRANCH=$env:APPVEYOR_REPO_BRANCH TRAVIS_COMMIT=$env:APPVEYOR_REPO_COMMIT ./upload.sh /c/projects/theinstaller/*.exe 2>/dev/null"
